-- MySQL Script generated by MySQL Workbench
-- Mon Oct 22 13:03:28 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TaxData`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TaxData` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TaxData` (
  `state` CHAR(2) NOT NULL,
  `zipcode` INT NOT NULL,
  `county` VARCHAR(100) NOT NULL,
  `incomeBracket` INT NOT NULL,
  `numReturns` INT NOT NULL,
  `totalIncome` INT NOT NULL,
  PRIMARY KEY (`state`, `zipcode`, `incomeBracket`),
  INDEX `taxState` (`state` ASC) INVISIBLE,
  INDEX `taxZip` (`zipcode` ASC) INVISIBLE,
  INDEX `taxCounty` (`county` ASC) VISIBLE,
  INDEX `taxCountyBracket` (`county` ASC, `incomeBracket` ASC) INVISIBLE,
  INDEX `taxZipBracket` (`zipcode` ASC, `incomeBracket` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Restaurants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Restaurants` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Restaurants` (
  `latitude` FLOAT NOT NULL,
  `longitude` FLOAT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `zipcode` INT NOT NULL,
  `county` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`latitude`, `longitude`),
  INDEX `restZip` (`zipcode` ASC) INVISIBLE,
  INDEX `restCounty` (`county` ASC) INVISIBLE,
  INDEX `restName` (`name` ASC) INVISIBLE,
  INDEX `restNameZip` (`name` ASC, `zipcode` ASC) INVISIBLE,
  INDEX `restNameCounty` (`name` ASC, `county` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
